//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoLib.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;RSAKeyValue&gt;&lt;Modulus&gt;qv9nytBm5+OrHzCv1l9rodwQ4/JC4nTwBVfhxWS749TLuTk3UNCNxpKTEwhFCKX/w4KJtfBc5ztvQMANdkqMgVABqPBTu8h4C1AaeyJJzdrAo4hYACeN+M4nhgdkZhSVQ/gr6scOR8rqO2SlxThEoWtr1y954sxmE5GCS3Q8FVgRSbOvOtDEGezwWe56CpsWMfYopnynjfkiYdpYhFAzhmu8DSI39qxILBnWNubSiKdcE1GFv1tPu8tJdyTtA4IHYQ8TIwIOCdZPnD10T/gBYhKuXFQqop3sxmxQ87PxiHjaQtvQpDRJPm0pcPN1Au4fwXhHfPYiTLnmP+bmQlnywQ==&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;x9Dc7xgbmFHn2HwaA7Ul/Ypsk+6g+BC/dEDEJVY2mw9E+B493Bs4wmVavwHpdNhYyJB8peggtcAebHUy2dL8qFzOHNZWSMVXDkmbFhStSoCb [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string privateKey {
            get {
                return ResourceManager.GetString("privateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SimmIV {
            get {
                object obj = ResourceManager.GetObject("SimmIV", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] SimmKey {
            get {
                object obj = ResourceManager.GetObject("SimmKey", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
